import type { Metadata } from "next"
import type { ReactNode } from "react"
import Link from "next/link"
import { DocsShell } from "@/components/docs/DocsShell"
import { DocsBreadcrumb } from "@/components/docs/DocsBreadcrumb"
import { DefinitionLeadOpening } from "@/components/docs/DefinitionLeadOpening"
import { AnchorHeading } from "@/components/docs/AnchorHeading"
import { RelatedTopicsList } from "@/components/docs/RelatedTopicsList"
import { JsonLd } from "@/components/seo/JsonLd"
import { reactNodeToText } from "@/lib/reactNodeToText"

export const metadata: Metadata = {
  alternates: { canonical: "/docs/faq" },
  title: "Frequently asked questions — INDXR.AI Docs",
  description:
    "Short answers to common questions about INDXR — captions versus AI transcription, formats, credits, languages, and what happens to your files.",
  openGraph: {
    title: "Frequently asked questions — INDXR.AI Docs",
    description:
      "Short answers to common questions about INDXR — captions versus AI transcription, formats, credits, and privacy.",
    type: "website",
    url: "https://indxr.ai/docs/faq",
  },
}

const A = "text-[var(--accent)] hover:underline"
const P = "text-[var(--fg-subtle)] leading-relaxed mb-4"

const faqs: { question: string; answer: ReactNode }[] = [
  {
    question: "Do I need an account?",
    answer: (
      <>
        Not for a single video. Without signing in you can extract the caption track from one video at
        a time and take the text as a plain TXT file. Everything else — AI transcription, playlists,
        uploads, the other six export formats, and the library that keeps your transcripts — needs a
        free account. See <Link href="/docs/quickstart" className={A}>Get your first transcript</Link>.
      </>
    ),
  },
  {
    question: "What does it cost?",
    answer: (
      <>
        Caption extraction is free, on any video, of any length. AI transcription, summaries and RAG
        JSON are paid for with prepaid credits, and credits never expire. New accounts start with a
        balance to try it. See <Link href="/docs/account/credits" className={A}>Credits</Link> for the
        rates and <Link href="/pricing" className={A}>Pricing</Link> for the packages.
      </>
    ),
  },
  {
    question: "What's the difference between captions and AI transcription?",
    answer: (
      <>
        Captions are the subtitle track a video already carries, usually generated by YouTube. AI
        transcription reads the audio and writes the transcript from scratch, returning punctuation and
        complete sentences. The choice sets the quality of everything you export afterwards. See{" "}
        <Link href="/docs/how-indxr-works" className={A}>How INDXR works</Link>.
      </>
    ),
  },
  {
    question: "What formats can I export?",
    answer: (
      <>
        Seven: TXT, Markdown, CSV, SRT, VTT, JSON and RAG JSON. TXT and Markdown each come with and
        without timestamps, which makes nine downloads in total. Only RAG JSON costs credits, and
        re-downloading anything you already generated is free. See{" "}
        <Link href="/docs/reference/export-formats" className={A}>Export formats</Link>.
      </>
    ),
  },
  {
    question: "Which languages does INDXR handle?",
    answer: (
      <>
        Caption extraction works in whatever language the video&apos;s track is in, and INDXR anchors on
        the original-language track rather than a translation. AI transcription covers a wide range of
        languages, and how well it performs differs per language. See{" "}
        <Link href="/docs/reference/accuracy" className={A}>Accuracy and languages</Link>.
      </>
    ),
  },
  {
    question: "What if a video has no captions?",
    answer: (
      <>
        INDXR does not check in advance whether a video carries a caption track. If the attempt comes
        back empty, INDXR says so and offers to transcribe the audio instead. In a playlist, videos
        without captions are skipped while the job runs and the credits held for them are returned. See{" "}
        <Link href="/docs/guides/single-video" className={A}>Single video</Link>.
      </>
    ),
  },
  {
    question: "Can I transcribe a whole playlist at once?",
    answer: (
      <>
        Yes. INDXR lists the videos it can reach and you choose per video whether to take the captions
        or transcribe the audio. The job keeps running after you close the tab, and finished transcripts
        appear in your library as they complete. See{" "}
        <Link href="/docs/guides/playlists" className={A}>Playlists</Link>.
      </>
    ),
  },
  {
    question: "Can I upload my own audio or video files?",
    answer: (
      <>
        Yes. An uploaded file has no caption track to fall back on, so uploads are always transcribed.
        There are limits on file size and length. See{" "}
        <Link href="/docs/guides/uploads" className={A}>Uploads</Link> and{" "}
        <Link href="/docs/reference/limits" className={A}>Limits</Link>.
      </>
    ),
  },
  {
    question: "What happens to my files?",
    answer: (
      <>
        Audio is deleted as soon as the transcription finishes; INDXR keeps no recording of it. The
        transcript itself stays in your library until you delete it. See{" "}
        <Link href="/privacy" className={A}>Privacy</Link>.
      </>
    ),
  },
  {
    question: "Is there an API?",
    answer: (
      <>
        No. INDXR is a web application; there is no public REST API. See{" "}
        <Link href="/docs/reference/limits" className={A}>Limits</Link>.
      </>
    ),
  },
]

export default function DocsFaqPage() {
  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((faq) => ({
      "@type": "Question",
      name: faq.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: reactNodeToText(faq.answer),
      },
    })),
  }

  return (
    <>
      <JsonLd schemas={[faqSchema]} />
      <DocsShell>
        <DocsBreadcrumb
          items={[
            { label: "Docs", href: "/docs" },
            { label: "Getting started", href: "/docs" },
            { label: "FAQ" },
          ]}
        />
        <h1 className="text-2xl font-bold text-[var(--fg)] mb-4">Frequently asked questions</h1>
        <DefinitionLeadOpening>
          Short answers to the questions people ask before their first transcript. Each one points to
          the page that carries the full answer.
        </DefinitionLeadOpening>

        {faqs.map((faq) => (
          <div key={faq.question}>
            <AnchorHeading as="h2">{faq.question}</AnchorHeading>
            <p className={P}>{faq.answer}</p>
          </div>
        ))}

        <RelatedTopicsList
          topics={[
            {
              label: "Get your first transcript",
              href: "/docs/quickstart",
              description: "the flow from URL to export",
            },
            {
              label: "How INDXR works",
              href: "/docs/how-indxr-works",
              description: "captions versus transcription, and why the choice carries downstream",
            },
            {
              label: "Credits",
              href: "/docs/account/credits",
              description: "rates, reservations and refunds",
            },
          ]}
        />
      </DocsShell>
    </>
  )
}
